name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'frontend_wasm/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: globoclimakeys
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Verifique se a versão está correta

      - name: Publish Project
        run: dotnet publish frontend_wasm/GloboClima.WebApp.Client/GloboClima.WebApp.Client.csproj -c Release -o release

      - name: Sync files to S3
        run: aws s3 sync ./release/wwwroot/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"